name: build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  release:
    types: [ published ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra:
          - "11.1.1"
          - "11.0.3"
          - "10.4"

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Install Ghidra ${{ matrix.ghidra }}
        uses: antoniovazquezblanco/setup-ghidra@v2.0.3
        with:
          version: ${{ matrix.ghidra }}

      - name: Build plugin via gradle
        run: gradle -PZIP_NAME_PREFIX=ghidra_${{matrix.version}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Ghidra_${{ matrix.ghidra }}_Cartographer
          path: dist/*Cartographer.zip

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4

      - name: Upload release ZIP
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh release upload ${{github.event.release.tag_name}} Ghidra_*/*.zip
